### ISSUE TITLE
Fix the go.sum file

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-controller#15]
With a recent push to the develop branch, there is an error related to the go.sum file:
https://github.com/k8-proxy/go-k8s-controller/runs/2352690080?check_suite_focus=true

go: github.com/gogo/protobuf@v1.3.2: missing go.sum entry; to add it:
	go mod download github.com/gogo/protobuf
Error: Process completed with exit code 1.

Please submit a fix

**Comment by GINAGC** [comment]
this is done
