### ISSUE TITLE
Create the service 1

### ISSUE THREAD

**Issue by azopat** [k8-proxy/go-k8s-controller#2]
As per the reference flow, please create a service 1 which will  :  
- Listen to the adaptation queue
- Get file details from the queue
- Upload that file to Minio
- Create signed URL from that file
- Put the information to Processing QUEUE (New queue to create)

Note : the adaptation queue already exist, look into the code here https://github.com/k8-proxy/rebuild-pods-controller to see all the information passed to adaptation queue.

**Comment by mahnouman** [comment]
This reference flow:
|
![new-rebuild-flow-v2](https://user-images.githubusercontent.com/5932628/107740191-340cea80-6d13-11eb-8894-3f324977bd1a.jpeg)

**Comment by azopat** [comment]
code is pushed here - https://github.com/k8-proxy/icap-service-1
