### ISSUE TITLE
fix the pull image issue

### ISSUE THREAD

**Issue by azopat** [k8-proxy/go-k8s-controller#21]
Warning  Failed     15m                  kubelet            Failed to pull image "k8serviceaccount/go-k8s-process:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/k8serviceaccount/go-k8s-process:latest": failed to resolve reference "docker.io/k8serviceaccount/go-k8s-process:latest": failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
  Normal   Pulling    13m (x4 over 15m)    kubelet            Pulling image "k8serviceaccount/go-k8s-process:latest"

**Comment by GINAGC** [comment]
this is done
