### ISSUE TITLE
Unit test k8s.io/client-go v11.0.0+incompatible

### ISSUE THREAD

**Issue by haitham911** [k8-proxy/go-k8s-controller#26]
in go-k8s-controller go.mod file I see k8s.io/client-go v11.0.0+incompatible  line 26
https://github.com/k8-proxy/go-k8s-controller/blob/main/go.mod
 incompatible mean client-go v11.0.0 it doesn't have go.mod in its source code. or has a version  higher 
https://github.com/kubernetes/client-go/tree/release-11.0
https://github.com/kubernetes/client-go
this release under Maintenance 
I can not  build unite test  because this release not run with test client kubernetes
https://github.com/kubernetes/client-go/tree/master/kubernetes/fake  
note  select go-client release depend on Compatibility: client-go <-> Kubernetes clusters

**Comment by azopat** [comment]
hi @mahnouman  i've updated the code to implement the latest client-go version.
I tested the new image on a cluster and it works well.
Here is the PR - https://github.com/k8-proxy/go-k8s-controller/pull/29
