### ISSUE TITLE
Stabilize number of processing pods

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-controller#42]
Currently the number of running processing pods fluctuates much, we need to stabilize it around the configured value.

**Comment by Lestat06** [comment]
@mahnouman need more info on how to test this one, also will be testing this from ck8s develop

**Comment by Lestat06** [comment]
@GINAGC this needs f2f so its blocked

**Comment by Lestat06** [comment]
@haitham911 the pods now fluctuate from 14 to 30, this was tested with scenario-1000, what is the excpected ration of the fluctuation?
FYI @GINAGC
